### PR TITLE
Android additions

### PR DESCRIPTION
**Pull request by miterosan**
Code fixes and simplying the project.
Also allowing the rotation of the screen.

### CODE REVIEW

**Comment by NexusX4** [comment]
is it keyboard supported?

**Comment by tangalbert919** [comment]
@NexusX4 stop asking me that. That's not my problem right now.

**Comment by miterosan** [comment]
I did not add keyboard support in this PR.
I wanted to do that in a seperate PR.

**Comment by miterosan** [comment]
I forgot to remove a log file I accidently commited <:

**Pull request merged**
